import React, { useState } from "react";
import {
  Plus,
  Download,
  Play,
  Pause,
  Copy,
  ArrowLeft,
  ArrowRight,
  Users,
  TrendingUp,
  Calendar,
  MapPin,
  MousePointer2,
  Eye,
  Sparkles,
  Trash2,
} from "lucide-react";
import { useApp } from "../store";
import {
  PageHead,
  Button,
  Tabs,
  SearchBox,
  Badge,
  Channel,
  Empty,
  navigate,
} from "../components/UI";
import { CreativePlayer } from "../components/Creative";
import { CampaignTable, Stats } from "./Dashboard";
import { uid, money, number, exportCSV } from "../data";
export default function Campaigns() {
  const { state } = useApp();
  const [filter, setFilter] = useState("All campaigns"),
    [search, setSearch] = useState("");
  const campaigns = state.campaigns
    .filter((c) => filter === "All campaigns" || c.status === filter)
    .filter((c) =>
      (c.name + " " + c.brand).toLowerCase().includes(search.toLowerCase()),
    );
  function download() {
    exportCSV(
      [
        [
          "Campaign",
          "Brand",
          "Status",
          "Channels",
          "Spend INR",
          "Impressions",
          "Clicks",
          "Leads",
        ],
        ...campaigns.map((c) => [
          c.name,
          c.brand,
          c.status,
          c.channels.join(" + "),
          c.spend,
          c.impressions,
          c.clicks,
          c.leads,
        ]),
      ],
      "adcraft-campaigns.csv",
    );
  }
  return (
    <>
      <PageHead
        title="Good ideas, out in the world."
        description="Your campaigns, from the first spark to the next customer."
      >
        <Button variant="secondary" icon={Download} onClick={download}>
          Export report
        </Button>
        <Button icon={Plus} onClick={() => navigate("/create")}>
          Create campaign
        </Button>
      </PageHead>
      <Stats campaigns={state.campaigns} />
      <div className="library-controls campaign-controls">
        <Tabs
          value={filter}
          onChange={setFilter}
          items={["All campaigns", "Active", "Draft", "Paused", "Completed"]}
        />
        <SearchBox
          value={search}
          onChange={setSearch}
          placeholder="Search campaigns"
        />
      </div>
      <section className="panel flush">
        <CampaignTable campaigns={campaigns} />
      </section>
    </>
  );
}
export function CampaignDetail({ id }) {
  const { state, update, notify } = useApp();
  const c = state.campaigns.find((c) => c.id === id);
  if (!c)
    return (
      <Empty
        title="Campaign not found"
        description="Choose a campaign from your workspace."
        action={
          <Button onClick={() => navigate("/campaigns")}>View campaigns</Button>
        }
      />
    );
  const asset = state.assets.find((a) => a.id === c.assetId);
  function patch(values) {
    update((s) => ({
      ...s,
      campaigns: s.campaigns.map((x) =>
        x.id === id ? { ...x, ...values } : x,
      ),
    }));
  }
  function simulate() {
    if (c.status !== "Active") {
      notify("Resume this campaign to simulate new activity.", "error");
      return;
    }
    const names = [
      "Maya Patel",
      "Kiran Rao",
      "Riya Menon",
      "Dev Shah",
      "Ishaan Kumar",
    ];
    const name = names[c.leads % names.length],
      source = c.channels[c.leads % c.channels.length];
    const lead = {
      id: uid(),
      name,
      email: "demo." + Date.now() + "@example.com",
      phone: "+91 00000 00000",
      campaignId: id,
      source,
      status: "New",
      date: new Date().toISOString(),
      notes: "Generated by the demo activity simulator.",
      mock: true,
    };
    update((s) => ({
      ...s,
      campaigns: s.campaigns.map((x) =>
        x.id === id
          ? {
              ...x,
              spend:
                x.spend +
                Math.min(100, Math.max(0, x.dailyBudget * x.days - x.spend)),
              impressions: x.impressions + 1420,
              clicks: x.clicks + 48,
              leads: x.leads + 1,
            }
          : x,
      ),
      leads: [lead, ...s.leads],
    }));
    notify("Demo activity added: 1 new lead and 48 clicks.");
  }
  function duplicate() {
    const copy = {
      ...c,
      id: uid(),
      name: c.name + " (copy)",
      status: "Draft",
      paid: false,
      spend: 0,
      impressions: 0,
      clicks: 0,
      leads: 0,
      createdAt: new Date().toISOString(),
    };
    update((s) => ({ ...s, campaigns: [copy, ...s.campaigns] }));
    notify("Campaign duplicated as a draft.");
    navigate("/review/" + copy.id);
  }
  return (
    <>
      <button
        className="text-button back-link"
        onClick={() => navigate("/campaigns")}
      >
        <ArrowLeft size={15} />
        All campaigns
      </button>
      <PageHead title={c.name} description={`${c.brand} · ${c.goal}`}>
        <Badge status={c.status}>{c.status}</Badge>
        <Button variant="secondary" icon={Copy} onClick={duplicate}>
          Duplicate
        </Button>
        {c.status === "Draft" ? (
          <Button onClick={() => navigate("/review/" + id)}>
            Review & launch
          </Button>
        ) : (
          <Button
            variant="secondary"
            icon={c.status === "Active" ? Pause : Play}
            onClick={() => {
              patch({ status: c.status === "Active" ? "Paused" : "Active" });
              notify(
                c.status === "Active"
                  ? "Campaign paused."
                  : "Campaign resumed.",
              );
            }}
          >
            {c.status === "Active" ? "Pause campaign" : "Resume campaign"}
          </Button>
        )}
      </PageHead>
      <Stats campaigns={[c]} />
      <div className="detail-layout">
        <section className="panel">
          <div className="section-title">
            <h2>Your campaign creative</h2>
            <button
              className="text-button"
              onClick={() => navigate("/editor/" + asset.id)}
            >
              Edit creative
              <ArrowRight size={14} />
            </button>
          </div>
          <div className="detail-creative">
            {asset && <CreativePlayer key={asset.id} asset={asset} />}
          </div>
          <p>{c.primaryText}</p>
        </section>
        <div>
          <section className="panel">
            <h2>The plan at a glance</h2>
            <dl className="detail-list">
              <div>
                <dt>Channels</dt>
                <dd className="channel-stack">
                  {c.channels.map((ch) => (
                    <Channel name={ch} key={ch} />
                  ))}
                </dd>
              </div>
              <div>
                <dt>Daily budget</dt>
                <dd>{money(c.dailyBudget)}</dd>
              </div>
              <div>
                <dt>Total budget</dt>
                <dd>{money(c.dailyBudget * c.days)}</dd>
              </div>
              <div>
                <dt>Duration</dt>
                <dd>{c.days} days</dd>
              </div>
              <div>
                <dt>Location</dt>
                <dd>{c.location}</dd>
              </div>
              <div>
                <dt>Audience</dt>
                <dd>
                  Ages {c.ageMin}–{c.ageMax}
                </dd>
              </div>
              <div>
                <dt>Cost per lead</dt>
                <dd>{c.leads ? money(c.spend / c.leads) : "—"}</dd>
              </div>
            </dl>
          </section>
          <section className="panel demo-activity">
            <span className="purple-icon">
              <Sparkles size={22} />
            </span>
            <h2>See your campaign in motion.</h2>
            <p>
              Add sample clicks, spend, and a new lead to explore the complete
              experience.
            </p>
            <Button
              icon={TrendingUp}
              onClick={simulate}
              disabled={c.status !== "Active"}
            >
              Simulate campaign activity
            </Button>
            <p className="demo-caption">
              Sample results only. No real ads or contacts.
            </p>
          </section>
          <section className="panel">
            <div className="section-title">
              <h2>New opportunities</h2>
              <button
                className="text-button"
                onClick={() => navigate("/leads?campaign=" + id)}
              >
                View leads
                <ArrowRight size={14} />
              </button>
            </div>
            {state.leads
              .filter((l) => l.campaignId === id)
              .slice(0, 3)
              .map((l) => (
                <div className="compact-lead" key={l.id}>
                  <span className="lead-avatar">
                    {l.name
                      .split(" ")
                      .map((s) => s[0])
                      .join("")}
                  </span>
                  <div>
                    <b>{l.name}</b>
                    <small>{l.email}</small>
                  </div>
                  <Badge status={l.status}>{l.status}</Badge>
                </div>
              ))}
            {!state.leads.some((l) => l.campaignId === id) && (
              <p className="muted">
                Your first lead is a little activity away.
              </p>
            )}
          </section>
        </div>
      </div>
    </>
  );
}
